delay_timer:      RubyChip::DelayTimer
draw_flag:        RubyChip::DrawFlag
graphics:         RubyChip::Graphics
keypad:           RubyChip::Keypad
memory:           RubyChip::Memory
register:         RubyChip::Register
index:            RubyChip::Index
program_counter:  RubyChip::ProgramCounter
stack:            RubyChip::Stack
sound_timer:      RubyChip::SoundTimer