"Gosu::Kb1": 0x1
"Gosu::Kb2": 0x2
"Gosu::Kb3": 0x3
"Gosu::Kb4": 0xC
"Gosu::KbQ": 0x4
"Gosu::KbW": 0x5
"Gosu::KbE": 0x6
"Gosu::KbR": 0xD
"Gosu::KbA": 0x7
"Gosu::KbS": 0x8
"Gosu::KbD": 0x9
"Gosu::KbF": 0xE
"Gosu::KbZ": 0xA
"Gosu::KbX": 0x0
"Gosu::KbC": 0xB
"Gosu::KbV": 0xF