- 00E0
- 00EE
- 1NNN
- 2NNN
- 3XNN
- 4XNN
- 5XY0
- 6XNN
- 7XNN
- 8XY0
- 8XY1
- 8XY2
- 8XY3
- 8XY4
- 8XY5
- 8XY6
- 8XY7
- 8XYE
- 9XY0
- ANNN
- BNNN
- CXNN
- DXYN
- EX9E
- EXA1
- FX0A
- FX07
- FX15
- FX18
- FX1E
- FX29
- FX33
- FX55
- FX65